Fix sdk publishLocal (#1670)
There was a compilation error in our scaladocs caused by a variable that
needed to be escaped

The error was:
```
[error] atala/prism-sdk/credentials/shared/src/main/scala/io/iohk/atala/prism/credentials/utils/Mustache.scala:22:60: Variable variable undefined in comment for class Mustache in class Mustache
[error]   *   val context: TemplateContext = (variable: String) => Some("$variable content")
```

Before:

```
  *   val context: TemplateContext = (variable: String) => Some("$variable content")
```

Now:

```
  *   val context: TemplateContext = (variable: String) => Some("\$variable content")
```

NOTE: IntelliJ shows the scaladoc with "\$variable" but the compiled
scaladoc looks fine (i.e. without the "\")